pub fn create_table_with_all_supported_data_types(table_name: &str) -> String {
    format!(
        r#"
        CREATE TABLE {table_name} (
            -- TODO: remove this and types in INSERT when table without primary key is supported.
            id SERIAL PRIMARY KEY,
            boolean BOOLEAN NOT NULL,
            boolean_null BOOLEAN, 
            int2 INT2 NOT NULL,
            int2_null INT2,
            int4 INT4 NOT NULL,
            int4_null INT4,
            int8 INT8 NOT NULL,
            int8_null INT8,
            char CHAR NOT NULL,
            char_null CHAR,
            text TEXT NOT NULL,
            text_null TEXT,
            varchar VARCHAR NOT NULL,
            varchar_null VARCHAR,
            bpchar BPCHAR NOT NULL,
            bpchar_null BPCHAR,
            float4 FLOAT4 NOT NULL,
            float4_null FLOAT4,
            float8 FLOAT8 NOT NULL,
            float8_null FLOAT8,
            bytea BYTEA NOT NULL,
            bytea_null BYTEA,
            timestamp TIMESTAMP NOT NULL,
            timestamp_null TIMESTAMP,
            timestamptz TIMESTAMPTZ NOT NULL,
            timestamptz_null TIMESTAMPTZ,
            numeric NUMERIC NOT NULL,
            numeric_null NUMERIC,
            jsonb JSONB NOT NULL,
            jsonb_null JSONB,
            date DATE NOT NULL,
            date_null DATE,
            point POINT NOT NULL,
            point_null POINT
        );
        INSERT INTO {table_name} (
            boolean,
            boolean_null,
            int2,
            int2_null,
            int4,
            int4_null,
            int8,
            int8_null,
            char,
            char_null,
            text,
            text_null,
            varchar,
            varchar_null,
            bpchar,
            bpchar_null,
            float4,
            float4_null,
            float8,
            float8_null,
            bytea,
            bytea_null,
            timestamp,
            timestamp_null,
            timestamptz,
            timestamptz_null,
            numeric,
            numeric_null,
            jsonb,
            jsonb_null,
            date,
            date_null,
            point,
            point_null
        ) VALUES (
            false,
            false,
            0,
            0,
            0,
            0,
            0,
            0,
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            0.0,
            0.0,
            0.0,
            0.0,
            '',
            '',
            '1970-01-01 00:00:00',
            '1970-01-01 00:00:00',
            '1970-01-01 00:00:00',
            '1970-01-01 00:00:00',
            0,
            0,
            '{{}}'::json,
            '{{}}'::json,
            '1970-01-01',
            '1970-01-01',
            '(0,0)',
            '(0,0)'
        );
        INSERT INTO {table_name} (
            boolean,
            boolean_null,
            int2,
            int2_null,
            int4,
            int4_null,
            int8,
            int8_null,
            char,
            char_null,
            text,
            text_null,
            varchar,
            varchar_null,
            bpchar,
            bpchar_null,
            float4,
            float4_null,
            float8,
            float8_null,
            bytea,
            bytea_null,
            timestamp,
            timestamp_null,
            timestamptz,
            timestamptz_null,
            numeric,
            numeric_null,
            jsonb,
            jsonb_null,
            date,
            date_null,
            point,
            point_null
        ) VALUES (
            true,
            null,
            1,
            null,
            1,
            null,
            1,
            null,
            '1',
            null,
            '1',
            null,
            '1',
            null,
            '1',
            null,
            1.0,
            null,
            1.0,
            null,
            '1',
            null,
            '1970-01-01 00:00:00',
            null,
            '1970-01-01 00:00:00',
            null,
            1,
            null,
            '{{ "1": 1 }}'::json,
            null,
            '1970-01-01',
            null,
            '(1,1)',
            null
        );
        "#,
    )
}
