[package]
name = "dozer-ingestion-connector"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dozer-types = { path = "../../dozer-types" }
futures = "0.3.28"
tokio = "1.32.0"
