app_name: dozer-samples-connectors-local-storage

connections:
  - config : !LocalStorage
      details:
        path: data
      tables:
        - !Table
            name: trips
            config: !Parquet
              path: trips
              extension: .parquet
    name: ny_taxi

sql: |
  SELECT 
    PULocationID as pickup_location, 
    DOLocationID as dropoff_location, 
    COUNT(PULocationID, DOLocationID) as total_trips, 
    MIN(trip_time) as min_trip_time,  
    MAX(trip_time) as max_trip_time 
  INTO trips_cache
  FROM trips
  GROUP BY PULocationID, DOLocationID
  HAVING COUNT(PULocationID, DOLocationID) > 1000;
sources:
  - name: trips
    table_name: trips
    connection: ny_taxi

endpoints:
  - name: trips_cache
    path: /trips
    table_name: trips_cache
    index:
      primary_key: 
        - pickup_location
        - dropoff_location
