storage_path: null
sources:
  - name: accounts
    table_name: accounts
    connection:
      db_type: Snowflake
      authentication: !SnowflakeAuthentication
        server: "{server}.eu-north-1.aws.snowflakecomputing.com"
        port: 443
        user: "{username}"
        password: "{password}"
        database: "{database}"
        schema: "{schema}"
        warehouse: "{warehouse}"
      name: accounts
    history_type: null
    refresh_config: RealTime
endpoints:
  - name: accounts
    path: /accounts
    enable_rest: false
    enable_grpc: true
    sql: select id from accounts;
    index:
      primary_key:
        - id
