storage_path: null
sources:
  - name: users
    table_name: users
    connection:
      db_type: Postgres
      authentication: !PostgresAuthentication
        user: postgres
        password: postgres
        host: localhost
        port: 5432
        database: users
      name: users
    history_type: null
    refresh_config: RealTime
endpoints:
  - name: users
    path: /users
    enable_rest: false
    enable_grpc: true
    sql: select id, email, phone from users where 1=1;
    index:
      primary_key:
        - id
