storage_path: null
sources:
  - name: accounts
    table_name: ACCOUNTS
    connection:
      db_type: Snowflake
      authentication: !SnowflakeAuthentication
        server: tx06321.eu-north-1.aws.snowflakecomputing.com
        port: 443
        user: karolisgud
        password: uQ@8S4856G9SHP6
        database: DOZER_TEST
        schema: PUBLIC
        warehouse: TEST
      name: accounts
    history_type: null
    refresh_config: RealTime
endpoints:
  - name: accounts
    path: /accounts
    enable_rest: false
    enable_grpc: true
    sql: select id, value from accounts;
    index:
      primary_key:
        - id
