[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.build-orchestrator]
command = "cargo"
args = ["build", "-p", "dozer-orchestrator", "--release", "--bin", "dozer"]

[tasks.reset-admin-db]
script_runner = "@shell"
script = '''
rm -rf ./dozer-admin/dozer.db && cd dozer-admin && diesel setup && diesel migration run
cd ..
'''

[tasks.checkout-ui]
script_runner = "@shell"
script = '''
rm -rf ./dozer-ui
gh repo clone getdozer/dozer-ui ./dozer-ui
cd dozer-ui
git checkout develop
yarn && yarn build
yarn global add serve
serve -s build  &
'''

[tasks.build-dozer-admin]
command = "cargo"
args = ["build", "-p", "dozer-admin", "--release", "--bin", "dozer-admin"]


[tasks.create-dozer-admin-config]
script_runner = "@shell"
script = '''
cp config/samples/dozer-admin-config.sample.yaml target/release/dozer-admin-config.yaml
'''

[tasks.start-dozer-admin]
script_runner = "@shell"
script = '''
target/release/dozer-admin -c target/release/dozer-admin-config.yaml  &
'''

[tasks.my-flow]
dependencies = [
    "build-orchestrator",
    "reset-admin-db",
    "create-dozer-admin-config",
    "start-dozer-admin",
    "checkout-ui"
]