version: '3.8'
services:
  db:
    container_name: orchestation-be-sqlite
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/

  api_server:
    build: ./
    ports:
      - "3001:3001"
    volumes:
      - ./:/usr/src/dozer-orchestration
      - ./db/:/sqlite/db/
    links:
      - db
    command: cargo watch -x run

volumes:
  db: