[package]
name = "dozer-sinks-bigquery"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dozer-api = { path = "../../dozer-api" }
dozer-types = { path = "../../dozer-types" }
dozer-log = { path = "../../dozer-log" }
dozer-core = { path = "../../dozer-core" }
dozer-recordstore = { path = "../../dozer-recordstore" }
itertools = "0.10.5"
futures-util = "0.3.28"
chrono = "0.4.31"
gcp-bigquery-client = "0.18.0"
object_store = { version = "0.9.0", features = ["gcp"] }
parquet = "48.0.1"
yup-oauth2 = "8.3.2"
bytes = "1.5.0"
html-escape = "0.2.13"
