app_name: working_app
connections:
  - authentication: !Ethereum
      filter:
        from_block: 0
        to_block: 1
        addresses: []
        topics: []
      wss_url: "{{ETH_WSS_URL}}"
      name: eth_logs
    db_type: Ethereum
    name: eth_logs
sql: |
  -- Eth stats table
  select block_number, sum(id) from eth_logs 
  into eth_stats
  group by block_number;

  -- Eth block stats
  select block_number, id  from eth_logs 
  into eth_block_stats
  group by block_number, id;

sources:
  - name: eth_logs
    table_name: eth_logs
    columns:
      - block_number
      - id
    connection: !Ref eth_logs
endpoints:
  - id: 1b44cca2-7631-4f0c-8b6e-254c08d28dae
    name: eth_stats
    table_name: eth_stats
    path: /eth/stats
    index:
      primary_key:
        - block_number
  - name: eth_logs
    path: /eth/logs
    table_name: eth_block_stats
    index:
      primary_key:
        - block_number
        - id
