app_name: working_app
connections:
  - authentication: !Ethereum
      filter:
        from_block: 0
        to_block: 1
        addresses: []
        topics: []
      wss_url: "{{ETH_WSS_URL}}"
      name: eth_logs
    db_type: Ethereum
    name: eth_logs
sources:
  - name: eth_logs
    table_name: eth_logs
    columns:
      - block_number
      - id
    connection: !Ref eth_logs
endpoints:
  - id: 1b44cca2-7631-4f0c-8b6e-254c08d28dae
    app_id: 5116e5e4-6963-47fe-b63c-e80ced1fbf29
    name: eth_stats
    path: /eth/stats
    sql: select block_number, sum(id) from eth_logs where 1=1 group by block_number;
    index:
      primary_key:
        - block_number
  - name: eth_logs
    path: /eth/logs
    sql: select block_number, id  from eth_logs where 1=1 group by block_number, id;
    index:
      primary_key:
        - block_number
        - id
