[package]
name = "dozer-ingestion-dozer"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dozer-ingestion-connector = { path = "../connector" }
dozer-log = { path = "../../dozer-log" }
