app_name: dozer-eth-dashboard
connections:
  - config: !Postgres
      user: postgres
      password: postgres
      host: localhost
      port: 5432
      database: eth_addresses
    name: eth_addresses

  - config: !Ethereum
      provider: !Log
        filter:
          from_block: 0
          to_block: 1
          addresses: [ ]
          topics: [ ]
        wss_url: "{{ETH_WSS_URL}}"
    name: eth_logs

sources:
  - name: eth_addresses
    table_name: eth_addresses
    connection: !Ref eth_addresses
    columns:
      - address
      - name
      - accounttype
      - contracttype
      - entity
      - label
      - tag1
      - tag2
      - tag3
      - tag4
      - tag5
      - tag6
  - name: eth_logs
    table_name: eth_logs
    connection: !Ref eth_logs
    columns:
      - id
      - address
      - block_hash
      - block_number

sql: |
  -- Get address stats combining data from postgres and ethereum connectors
  WITH eth_result AS (
    SELECT address
    FROM eth_addresses
    UNION
    SELECT address
    FROM eth_logs
  )
  SELECT address
  INTO eth_result_map
  FROM eth_result;

endpoints:
  - name: addresses
    path: /addresses
    table_name: eth_result_map
    index:
      primary_key:
        - address
