apiVersion: batch/v1
kind: Job
metadata:
  name: dozer-migrate
  namespace: dozer
spec:
  template:
    spec:
      containers:
      - name: dozer-migrate
        image: ramitabh/dozer:local
        command: ["dozer", "migrate"]
        volumeMounts:
        - name: data
          mountPath: /usr/dozer
        - name: dozer
          mountPath: /usr/app_data
        stdin: true
        tty: true
      restartPolicy: Never
      volumes:
      - name: data
        hostPath:
          path: /data/Dozer/dozer/dozer-k8/dozer_data
      - name: dozer
        persistentVolumeClaim:
            claimName: dozer-pvc
  backoffLimit: 0