version: '3.9'
services:
  dozer:
    container_name: dozer
    build: ../
    ports:
      # REST APIs are published on port 8080
      - "8080:8080"
      # gRPC are available over 50051
      - "50051:50051"
    volumes:
      - ./dozer-config.yaml:/usr/dozer/dozer-config.yaml
      - ./.dozer:/usr/dozer/.dozer
    networks: ["dozer_net"]

networks:
  dozer_net:
    enable_ipv6: true
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
        - subnet: fd00:0:0:1::/64
          gateway: fd00:0:0:1::1

volumes:
  sample-data: