app_name: dozer-config-eth
api:
  rest:
    port: 8080
    url: "[::0]"
    cors: true
  grpc:
    port: 50051
    url: "[::0]"
    cors: true
    web: true
  auth: false
  internal:
    port: 50052
    host: "[::1]"
connections:
  - name: all_events
    db_type: Kafka
    authentication: !Ethereum
      wss_url: wss://localhost:8545
      filter:
        addresses:
        topics:
sources:
  - name: all_events
    table_name: eth_logs
    connection: !Ref all_events
    history_type: null
    refresh_config: !RealTime {}
endpoints:
  - name: events
    path: /events
    enable_rest: false
    enable_grpc: true
    sql: select block_number, id from eth_logs group by id, block_number;
    index:
      primary_key:
        - block_number
