app_name: dozer-config-kafka
api:
  rest:
    port: 8080
    url: "[::0]"
    cors: true
  grpc:
    port: 50051
    url: "[::0]"
    cors: true
    web: true
  auth: false
  internal:
    port: 50052
    host: "[::1]"
connections:
  - name: all_events
    db_type: Kafka
    authentication: !KafkaAuthentication
      broker: localhost:9092
      topic: dbserver1.inventory.customers
sources:
  - name: all_events
    table_name: dbserver1.inventory.customers
    connection: !Ref all_events
    history_type: null
    refresh_config: RealTime
endpoints:
  - name: customers
    path: /customers
    enable_rest: false
    enable_grpc: true
    sql: select id, first_tame from customers;
    index:
      primary_key:
        - id
