app_name: dozer-config-sample
api:
  rest:
    port: 8080
    url: "[::0]"
    cors: true
  grpc:
    port: 50051
    url: "[::0]"
    cors: true
    web: true
  auth: false
  api_internal:
    port: 50052
    host: '[::1]'
  pipeline_internal:
    port: 50053
    host: '[::1]'
connections:
  - db_type: Postgres
    authentication: !Postgres
      user: postgres
      password: postgres
      host: localhost
      port: 5432
      database: users
    name: users
sources:
  - name: users
    table_name: users
    columns:
      - id
      - email
      - phone
    connection: !Ref users
    history_type: null
    refresh_config: !RealTime {}
endpoints:
  - id: null
    name: users
    path: /users
    sql: select id, email, phone from users where 1=1;
    index:
      primary_key:
        - id
