version: '3.9'
services:
  dozer:
    container_name: dozer
    depends_on:
      postgres:
        condition: service_healthy

    links:
      - postgres
    
    image: public.ecr.aws/k7k6x1d4/dozer:latest
    ports:
      # REST APIs are published on port 8080
      - "8080:8080"
      # gRPC are available over 50051
      - "50051:50051"
    volumes:
      - ./dozer-config.yaml:/usr/dozer/dozer-config.yaml
      - ./.dozer:/usr/dozer/.dozer
    command: "dozer -c /usr/dozer/dozer-config.yaml"
    stdin_open: true 
    tty: true

  postgres:
    container_name: quick-start-postgres
    image: public.ecr.aws/k7k6x1d4/dozer-samples-pg-stocks
    command: postgres -c hba_file=/var/lib/stock-sample/pg_hba.conf
    environment:
      POSTGRES_DB: stocks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      ALLOW_IP_RANGE: 0.0.0.0/0
    ports:
      - '5434:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready  -h 0.0.0.0 -U postgres -d stocks" ]
      interval: 5s
      timeout: 5s
      retries: 5  

volumes:
  sample-data: