version: '3.9'
services:
  postgres:
    container_name: quick-start-postgres
    image: public.ecr.aws/k7k6x1d4/dozer-samples-pg-stocks
    command: postgres -c hba_file=/var/lib/stock-sample/pg_hba.conf
    environment:
      POSTGRES_DB: stocks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      ALLOW_IP_RANGE: 0.0.0.0/0
    ports:
      - '5434:5432'
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres  -h 0.0.0.0 -d stocks"
        ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  sample-data:
