version: '3.8'
services:
  postgres:
    container_name: 1-hypercharge-postgres-sample
    image: debezium/postgres:13
    volumes:
      - ./pg_hba.conf:/var/lib/stock-sample/pg_hba.conf
      - ./scripts/init_stocks.sql:/docker-entrypoint-initdb.d/init_stocks.sql
      - ./data/stock_price.csv:/var/lib/stock-sample/data/stock_price.csv
    command: postgres -c hba_file=/var/lib/stock-sample/pg_hba.conf
    environment:
      POSTGRES_DB: stocks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      ALLOW_IP_RANGE: 0.0.0.0/0
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d stocks" ]
      interval: 5s
      timeout: 5s
      retries: 5
