version: '3.8'
services:
  dozer-postgres:
    depends_on:
      - postgres
    links:
      - postgres
    container_name: 1-hypercharge-postgres-dozer
    image: public.ecr.aws/k7k6x1d4/dozer:latest
    ports:
      - "8080:8080"
      - "50051:50051"
    volumes:
      - ./dozer-config.yaml:/usr/dozer/dozer-config.yaml
    command: "-c /usr/dozer/dozer-config.yaml"

  postgres:
    container_name: 1-postgres-sample
    image: debezium/postgres:13
    build:
      dockerfile: postgres.Dockerfile
    volumes:
      - ./pg_hba.conf:/var/lib/stock-sample/pg_hba.conf
      - ./scripts/init_stocks.sql:/docker-entrypoint-initdb.d/init_stocks.sql
    command: postgres -c hba_file=/var/lib/stock-sample/pg_hba.conf
    environment:
      POSTGRES_DB: stocks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      ALLOW_IP_RANGE: 0.0.0.0/0
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d stocks" ]
      interval: 5s
      timeout: 5s
      retries: 5
