version: '3.8'
services:
  dozer-postgres:
    links:
      - postgres
    container_name: 1-dozer
    build:
      dockerfile: ./postgres.Dockerfile
    ports:
      - "8080:8080"
      - "50052:50052"
      - "50051:50051"
    volumes:
      - ./../../../config/log4rs.sample.yaml:/usr/dozer/log4rs.yaml
      - ./dozer-config.yaml:/usr/dozer/dozer-config.yaml
    command: ""
  postgres:
    container_name: 1-postgres
    image: debezium/postgres:13
    volumes:
      - ./pg_hba.conf:/var/lib/stock-sample/pg_hba.conf
      - ./scripts/init_stocks.sql:/docker-entrypoint-initdb.d/init_stocks.sql
      - ./data/stock_price.csv:/var/lib/stock-sample/data/stock_price.csv
      - ./data/symbols_valid_meta.csv:/var/lib/stock-sample/data/symbols_valid_meta.csv
    command: postgres -c hba_file=/var/lib/stock-sample/pg_hba.conf
    environment:
      POSTGRES_DB: stocks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      ALLOW_IP_RANGE: 0.0.0.0/0
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d stocks" ]
      interval: 5s
      timeout: 5s
      retries: 5
