app_name: 1-hypercharge-postgres-sample
connections:
  - db_type: Postgres
    authentication: !Postgres
      user: postgres
      password: postgres
      host: host.docker.internal
      port: 5434
      database: stocks
    name: stocks
sources:
  - name: stocks
    table_name: stocks
    columns:
      - id
      - ticker
      - date
      - open
      - high
      - low
      - close
      - adj_close
      - volume
    connection: !Ref stocks
  - name: stocks_meta
    table_name: stocks_meta
    columns:
      - nasdaq_traded
      - symbol
      - security_name
      - listing_exchange
      - market_category
      - etf
      - round_lot_size
      - test_issue
      - financial_status
      - cqs_symbol
      - nasdaq_symbol
      - next_shares
    connection: !Ref stocks
endpoints:
  - name: stocks
    path: /stocks
    sql: select id, ticker, date, open, high, low, close, adj_close, volume from stocks;
    index:
      primary_key:
        - id
  - id: null
    name: stocks_meta
    path: /stocks-meta
    sql: select symbol, security_name from stocks_meta;
    index:
      primary_key:
        - symbol