app_name: 1-hypercharge-postgres-sample
api:
  rest:
    port: 8080
    url: "[::0]"
    cors: true
  grpc:
    port: 50051
    url: "[::0]"
    cors: true
    web: true
  auth: false
  internal:
    port: 50052
    host: "[::1]"
connections:
  - db_type: Postgres
    authentication: !PostgresAuthentication
      user: postgres
      password: postgres
      host: localhost
      port: 5432
      database: stocks
    name: stocks
sources:
  - name: stocks
    table_name: stocks
    columns:
      - id
      - ticker
      - date
      - open
      - high
      - low
      - close
      - adj_close
      - volume
    connection: !Ref stocks
    history_type: null
    refresh_config: RealTime
  - name: stocks_meta
    table_name: stocks_meta
    columns:
      - nasdaq_traded
      - symbol
      - security_name
      - listing_exchange
      - market_category
      - etf
      - round_lot_size
      - test_issue
      - financial_status
      - cqs_symbol
      - nasdaq_symbol
      - next_shares
    connection: !Ref stocks
    history_type: null
    refresh_config: RealTime
endpoints:
  - id: null
    name: stocks
    path: /stocks
    sql: select id, ticker, date, open, high, low, close, adj_close, volume from stocks where 1=1;
    index:
      primary_key:
        - id
  - id: null
    name: stocks_metas
    path: /stocks-metas
    sql: select symbol, security_name from stocks_meta where 1=1;
    index:
      primary_key:
        - symbol
