app_name: hypercharge-postgres-sample
api:
  rest:
    port: 8080
    url: "[::0]"
    cors: true
  grpc:
    port: 50051
    url: "[::0]"
    cors: true
    web: true
  auth: false
  internal:
    port: 50052
    host: "[::1]"
connections:
  - db_type: Postgres
    authentication: !PostgresAuthentication
      user: postgres
      password: postgres
      host: localhost
      port: 5432
      database: stocks
    name: stocks
sources:
  - name: stocks
    table_name: stocks
    columns:
      - id
      - ticker
      - date
      - open
      - high
      - low
      - close
      - adj_close
      - volume
    connection: !Ref stocks
    history_type: null
    refresh_config: RealTime
endpoints:
  - id: null
    name: stocks
    path: /stocks
    sql: select id, ticker, date, open from stocks where 1=1;
    index:
      primary_key:
        - id
