app_name: 1-hypercharge-postgres-sample
flags:
  push_events: true
connections:
  - config: !Postgres
      user: postgres
      password: postgres
      host: localhost
      port: 5434
      database: stocks
    name: stocks
sources:
  - name: stocks
    table_name: stocks
    columns:
      - id
      - ticker
      - date
      - open
      - high
      - low
      - close
      - adj_close
      - volume
    connection: !Ref stocks
  - name: stocks_meta
    table_name: stocks_meta
    columns:
      - nasdaq_traded
      - symbol
      - security_name
      - listing_exchange
      - market_category
      - etf
      - round_lot_size
      - test_issue
      - financial_status
      - cqs_symbol
      - nasdaq_symbol
      - next_shares
    connection: !Ref stocks

sql: |
  -- transformation made on top of `stocks` table data
  SELECT
    id,
    AVG(open),
    AVG(close),
    low,
    volume 
  INTO stocks_data
  FROM stocks
  GROUP BY id;

endpoints:
  - name: stocks
    path: /stocks
    table_name: stocks_data
    index:
      primary_key:
        - id
  - name: stocks_meta
    path: /stocks-meta
    # direct selecting all columns at the source level for `stocks_meta`
    table_name: stocks_meta
    index:
      primary_key:
        - symbol
