name: Setup snowflake and kafka (debezium)

runs:
  using: "composite"
  steps:
    - name: Install Snowflake ODBC driver
      shell: bash
      run: curl ${SNOWFLAKE_DRIVER_URL} -o snowflake_driver.deb && sudo dpkg -i snowflake_driver.deb
      env:
        SNOWFLAKE_DRIVER_URL: https://sfc-repo.snowflakecomputing.com/odbc/linux/2.25.7/snowflake-odbc-2.25.7.x86_64.deb


    - name: ODBC
      shell: bash
      run: odbcinst -j

    - name: ODBC 2
      shell: bash
      run: cat /etc/odbcinst.ini

