refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d} - {m}{n}"
  api:
    kind: file
    path: "logs/api.log"
    encoder:
      pattern: "{d} - {m}{n}"
  app:
    kind: file
    path: "logs/app.log"
    encoder:
      pattern: "{d} - {m}{n}"
root:
  level: info
  appenders:
    - stdout
loggers:
  dozer_sql:
    level: info
    appenders:
      - app
  dozer_core:
    level: info
    appenders:
      - app
  dozer_ingesetion:
    level: info
    appenders:
      - app
  dozer_api:
    level: info
    appenders:
      - api
