name: users
table_name: users
connection:
  name: products_test
  db_type: Postgres
  authentication: !PostgresAuthentication
  user: ${KAFKA_POSTGRES_USER}
  password: ${KAFKA_POSTGRES_PASSWORD}
  host: ${KAFKA_POSTGRES_HOST}
  port: ${KAFKA_POSTGRES_PORT}
  database: ${KAFKA_POSTGRES_DATABASE}
history_type: null
refresh_config: RealTime
