version: '3.9'
services:
  dozer:
    container_name: dozer-dev
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
    image: public.ecr.aws/getdozer/dozer:dev
    ports:
      # REST APIs are published on port 8080
      - "8080:8080"
      # gRPC are available over 50051
      - "50051:50051"
    volumes:
      - ./dozer-config.yaml:/usr/dozer/dozer-config.yaml
      - ./.dozer:/usr/dozer/.dozer
    command: "dozer -c /usr/dozer/dozer-config.yaml"
    stdin_open: true
    tty: true

  postgres:
    container_name: banking-postgres
    image: debezium/postgres:13
    volumes:
      - ./pg_hba.conf:/var/lib/banking/pg_hba.conf
      - ./scripts/banking_data.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c hba_file=/var/lib/banking/pg_hba.conf
    environment:
      POSTGRES_DB: banking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      ALLOW_IP_RANGE: 0.0.0.0/0
    ports:
      - '5433:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h 0.0.0.0 -U postgres -d banking" ]
      interval: 10s
      timeout: 60s
      retries: 30

volumes:
  sample-data:
