apiVersion: apps/v1
kind: Deployment
metadata:
  name: dozer-app
  namespace: dozer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dozer-app
  template:
    metadata:
      labels:
        app: dozer-app
    spec:
      containers:
      - name: dozer-app
        image: ramitabh/dozer:local
        command: ["dozer", "app", "run"]
        ports:
        - containerPort: 50052
        volumeMounts:
        - name: data
          mountPath: /usr/dozer
        - name: dozer
          mountPath: /usr/app_data
        stdin: true
        tty: true
      volumes:
      - name: data
        hostPath:
          path: /data/Dozer/dozer/dozer-k8/dozer_data
      - name: dozer
        persistentVolumeClaim:
            claimName: dozer-pvc
    
