FROM ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main@sha256:b4f5bf74812f9bb6516140d4b83d1f173c2d5ce0523f3e1c2253d99d851c734f

ENV PKG_CONFIG_ALLOW_CROSS="true"

RUN dpkg --add-architecture arm64 && \
    apt-get update && \
    apt-get install --assume-yes clang-8 libclang-8-dev binutils-aarch64-linux-gnu zlib1g-dev:arm64 unzip

# INSTALL PROTOBUF
ENV PROTOBUF_FILE_NAME=protoc-3.18.2-linux-x86_64.zip
RUN curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v3.18.2/${PROTOBUF_FILE_NAME}
ENV PROTOC_DIR=/usr/local/protoc
RUN unzip ${PROTOBUF_FILE_NAME} -d ${PROTOC_DIR}
RUN chmod -R a+xr ${PROTOC_DIR}
ENV PROTOC=${PROTOC_DIR}/bin/protoc
RUN rm ${PROTOBUF_FILE_NAME}
