FROM ghcr.io/cross-rs/x86_64-unknown-linux-gnu:main@sha256:bf0cd3027befe882feb5a2b4040dc6dbdcb799b25c5338342a03163cea43da1b

RUN apt-get update && \
    apt-get install --assume-yes clang libclang-dev binutils-aarch64-linux-gnu unzip

# INSTALL PROTOBUF
ENV PROTOBUF_FILE_NAME=protoc-3.18.2-linux-x86_64.zip
RUN curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v3.18.2/${PROTOBUF_FILE_NAME}
RUN unzip ${PROTOBUF_FILE_NAME} -d /usr/local/protoc
ENV PROTOC_DIR=/usr/local/protoc
RUN unzip ${PROTOBUF_FILE_NAME} -d ${PROTOC_DIR}
RUN chmod -R a+xr ${PROTOC_DIR}
ENV PROTOC=${PROTOC_DIR}/bin/protoc
RUN rm ${PROTOBUF_FILE_NAME}
