home_dir: /usr/app_data/app_data
connections:    
  - config : !LocalStorage
      details:
        path: /usr/dozer/data
      tables:
        - !Table
          name: trips
          prefix: /trips
          file_type: parquet
          extension: .parquet
    name: ny_taxi
api:
  rest:
    port: 8080
  grpc:
    port: 50051
  app_grpc:
    port: 50052
    host: dozer-app-svc.dozer
sql: |
  SELECT 
    PULocationID as pickup_location, 
    DOLocationID as dropoff_location, 
    COUNT(PULocationID, DOLocationID) as total_trips, 
    MIN(trip_time) as min_trip_time,  
    MAX(trip_time) as max_trip_time 
  INTO trips_cache
  FROM trips
  GROUP BY PULocationID, DOLocationID
  HAVING COUNT(PULocationID, DOLocationID) > 1000;

sources:
  - name: trips
    table_name: trips
    connection: !Ref ny_taxi
    columns:

endpoints:
  - name: trips_cache
    path: /trips
    table_name: trips_cache
    index:
      primary_key: 
        - pickup_location
        - dropoff_location