app_name: dozer-ingest-users
connections:
  - config: !Grpc
      schemas: !Inline |
        {
          "users": {
            "schema": {
              "fields": [
                {
                  "name": "id",
                  "typ": "Int",
                  "nullable": false
                },
                {
                  "name": "name",
                  "typ": "String",
                  "nullable": true
                },
                {
                  "name": "json",
                  "typ": "Json",
                  "nullable": true
                }
              ]
            }
          }
        }
    name: ingest

sources:
  - name: users
    table_name: users
    connection: ingest

endpoints:
  - name: users
    path: /users
    table_name: users
    index:
