version: '3.9'
services:
  dozer:
    image: public.ecr.aws/getdozer/dozer:dev
    environment:
      - SN_SERVER
      - SN_USER
      - SN_PASSWORD
      - SN_DATABASE
      - SN_WAREHOUSE
    ports:
      # REST APIs are published on port 8080
      - "8080:8080"
      # gRPC are available over 50051
      - "50051:50051"
    volumes:
      - ./dozer-config.yaml:/usr/dozer/dozer-config.yaml
      - ./.dozer:/usr/dozer/.dozer
    stdin_open: true
    tty: true