[package]
name = "aerospike-client-sys"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"

[lib]
doctest = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.69.4"
