container_name: hypercharge-postgres
command: postgres -c hba_file=/var/lib/stock-sample/pg_hba.conf
environment:
  - POSTGRES_DB=stocks
  - POSTGRES_USER=postgres
  - POSTGRES_PASSWORD=postgres
  - ALLOW_IP_RANGE=0.0.0.0/0
ports:
  - target: 5432
    published: 5434
healthcheck:
  test: [ "CMD-SHELL", "pg_isready -U postgres -h 0.0.0.0 -d stocks" ]
  interval: 5s
  timeout: 5s
  retries: 5
