name: Dozer Test

on:
  push:
    branches:
      - test-cicd
  pull_request:
    branches:
      - test-cicd

env:
  CARGO_TERM_COLOR: always

jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy

      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - name: Test
        run: |
          cargo install diesel_cli --no-default-features --features sqlite
          cargo test

      - name: Lint
        run: |
          cargo fmt --all -- --check
          cargo clippy -- -D warnings

      - name: Build documentation
        env:
          RUSTFLAGS: "--cfg doc_cfg"
          RUSTDOCFLAGS: "--cfg doc_cfg"
        run:
          cargo +nightly doc --manifest-path ./Cargo.toml --workspace
