name: Dozer General

on:
  issues:
    types: [opened, edited, milestoned]
  pull_request:
    branches: [main, release]
  pull_request_review_comment:
    types: [created, deleted]
  pull_request_review:
    types: [submitted]
concurrency:
  group: ${{ github.ref }}-general
  cancel-in-progress: true

jobs:
  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_GITHUB_WEBOOK }}
        uses: Ilshidur/action-discord@master
